# Generated by Django 3.2.7 on 2021-10-02 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='dimension',
            field=models.CharField(choices=[('gram', 'г'), ('piece', 'шт'), ('ml', 'мл')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Value cannot be lower than 1')]),
        ),
    ]
